### ISSUE TITLE
Name/Type of validator is set wrong if column has more than one validator

### ISSUE THREAD

**Issue by mkesicki** [mkesicki/excel_validator#5]
It is always set for first validator for column example:
```yml
        C:
            - Type:
                type: integer
                message: "Message"
                trim: true
                
        - Conditional:
                message: "Message"
                fieldB: "C"
                operator: "lambda c, d: (False if (c > d) else True)"
                trim: true 
        D:
            - Type:
                type: integer
                message: "Message"
                trim: true
```
in this case conditional validator will be not set
